inputFile:
  'D:\\git\\university\\input.csv'

logging:
  level: DEBUG
  appenders:
    - type: console
      threshold: DEBUG
      target: stderr
    - type: file
      threshold: ERROR
      currentLogFilename: ./logs/university-error.log
      archivedLogFilenamePattern: ./logs/university-error-%d.log.gz
      archivedFileCount: 5
      timeZone: UTC